import fs from 'fs';

export default function createPackageJson(projectName: string) {
  const packageJsonContent = {
    name: projectName,
    version: '1.0.0',
    type: 'module',
    main: './src/index.ts',
    scripts: {
      start: 'packlify-server',
      dev: 'packlify-dev-server',
      build: 'npm run build:react && npm run build:server',
      'build:server': 'packlify-build-server',
      'build:react': 'npm run build:react:client && npm run build:react:ssr',
      'build:react:ssr': 'packlify-build-ssr',
      'build:react:client': 'packlify-build-client',
      format: 'packlify-format-write',
      'format:check': 'packlify-format-check',
      lint: 'packlify-lint',
      test: 'vitest --run',
      'test:watch': 'vitest',
      'test:coverage': 'vitest --coverage',
      typecheck: 'tsc --noEmit',
    },
    license: 'MIT',
    dependencies: {
      '@packlify/client': '^0.0.0-alpha.1',
      '@packlify/core': '^0.0.4',
      axios: '^1.2.3',
      classnames: '^2.3.2',
      'cookie-parser': '^1.4.6',
      dotenv: '^16.0.3',
      express: '^4.18.2',
      react: '^18.2.0',
      'react-dom': '^18.2.0',
      'react-router-dom': '^6.15.0',
    },
    devDependencies: {
      '@packlify/config-build': '^0.0.1-alpha.0',
      '@packlify/config-format': '^0.1.2-alpha.1',
      '@types/cookie-parser': '^1.4.3',
      '@types/express': '^4.17.15',
      '@types/node': '^18.11.18',
      '@types/react': '^18.0.26',
      '@types/react-dom': '^18.0.10',
      autoprefixer: '^10.4.13',
      eslint: '^8.48.0',
      'eslint-config-packlify': '0.1.3-alpha.1',
      nodemon: '^3.0.1',
      postcss: '^8.4.21',
      tailwindcss: '^3.2.4',
      'ts-node': '^10.9.1',
      'tsconfig-paths': '^4.1.2',
      typescript: '^4.9.4',
      vite: '^4.4.9',
    },
  };

  fs.writeFileSync(`./${projectName}/package.json`, JSON.stringify(packageJsonContent, null, 2));
}
